### ISSUE TITLE
Add different graphics

### ISSUE THREAD

**Issue by sgharms** [learn-co-curriculum/cli-essentials-bash-intro#3]
@drakeltheryuujin I added some TODOs here. I want a pic of what a mainframe architecture would look like, e.g. (we may have to draw this, it's copyrighted)...

https://goo.gl/images/sxE66Q  (for the first todo)

and then something where the local Terminal emulator loops back to the laptop that it's running on...

**Comment by drakeltheryuujin** [comment]
Done and done!
